export const SET_BANNER_ARRAY = 'SET_BANNER_ARRAY';
export const GET_MOVIE_LIST = 'GET_MOVIE_LIST';
export const GET_CURRENT_MOVIES = 'GET_CURRENT_MOVIES';
export const GET_COMING_MOVIES = 'GET_COMING_MOVIES';
export const GET_CINEMA_LIST = 'GET_CINEMA_LIST';